""""""


class lcl:
    user = "user"
    name = "name"
    phone = "phone"
    field = "field"
    email = "email"
    users = "users"
    error = "error"
    token = "token"
    status = "status"
    errors = "errors"
    message = "message"
    user_id = "user_id"
    creator = "creator"
    dynamic = "dynamic"
    default = "default"
    testing = "testing"
    message = "message"
    project = "project"
    datetime = "datetime"
    production = "production"
    production = "production"
    development = "development"
    description = "description"
    organisations = "organisations"
    documentation = "documentation"
    data_visualization = "data_visualization"


class ccl:
    USER = "User"
    ACTIVE = "Active"
    SUCCESS = "Success"
    ORGANISATION = "Organisation"


class ucl:
    WAT = "WAT"
    SECRET_KEY = "SECRET_KEY"
    COMMIT_HASH = "COMMIT_HASH"
    DATABASE_URL = "DATABASE_URL"
    PRODUCTION_ENV = "PRODUCTION_ENV"
    APP_SECRET_KEY = "APP_SECRET_KEY"
    JWT_SECRET_KEY = "JWT_SECRET_KEY"
    SENTRY_DSN_FOR_HNG = "SENTRY_DSN_FOR_HNG"
    HNG11_T2_DEV_POSTGRESQL_DATABASE_URI = "HNG11_T2_DEV_POSTGRESQL_DATABASE_URI"
    HNG11_T2_PROD_POSTGRESQL_DATABASE_URI = "HNG11_T2_PROD_POSTGRESQL_DATABASE_URI"
    HNG11_T2_TEST_POSTGRESQL_DATABASE_URI = "HNG11_T2_TEST_POSTGRESQL_DATABASE_URI"
