"""Remove unique=True from Organisation.name

Revision ID: b754d4142fb4
Revises: dd9746f7c6cf
Create Date: 2024-07-07 00:00:07.393626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b754d4142fb4'
down_revision = 'dd9746f7c6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint('organisations_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_unique_constraint('organisations_name_key', ['name'])

    # ### end Alembic commands ###
